### ISSUE TITLE
[1.12] Null pointer exception

### ISSUE THREAD

**Issue by MasterEnderman** [TinyModularThings/Player-Weight#10]
Crash-Report: https://paste.dimdev.org/etapebaduc.mccrash
Player Weight: 1.4
Forge: 14.23.5.2815

**Comment by Speiger** [comment]
I know this sounds weird but this is not Playerweights issue since it only gets the Inventory via Forges Capabilities, which is basically overrideable by anything with ASM. I have no control over that.

Sry but some other mod causes that i get wrong information. I Even check if a mod would throw in a Null Inventory since that is a possiblity, but someone dropped in a Inventory Wrapper with a nullObject, which my system can not detect (and is also impossible to detect in all scenarios)

**Comment by MasterEnderman** [comment]
Could a Mod like Astikor Carts could cause something like this? because every time i try to sit on a cart the game crashes with the error shown above.
https://minecraft.curseforge.com/projects/astikorcarts

**Comment by issork** [comment]
Thank you for reporting this, it is indeed an issue on my end within AstikorCarts.
I will investigate and should be able to fix it soon. For now, you will have to play without AstikorCarts.

**Comment by Speiger** [comment]
good that it is solved.
