### ISSUE TITLE
Player weight Setting up via the gui does not work

### ISSUE THREAD

**Issue by lairdoghfst** [TinyModularThings/Player-Weight#17]
I tried using the mod's graphic editor to adjust the weight of the block but nothing came out I tried everything could you show me how it should be and it's not quite clear how.
I tried to make a stone weight 1kg but not what did not work I tried everything

**Comment by Speiger** [comment]
It only creates the file. Its not automatically added in the config. So that you can turn them on and off.

**Comment by lairdoghfst** [comment]
> Это только создает файл. Его не добавляется автоматически в конфиге. Так что вы можете включить их и выключить.

А как включить

**Comment by lairdoghfst** [comment]
And how to turn it on ?

**Comment by Speiger** [comment]
in the config file there is a section thats called "WeightFiles" in there you put in the fileName+extension
(so example.xml or example.txt) and then it will be loaded.

**Comment by lairdoghfst** [comment]
How is the mod doing with client-server synchronization?

**Comment by Speiger** [comment]
you need to do that manually.

**Comment by lairdoghfst** [comment]
Do I need to manually install the config on the server?

**Comment by Speiger** [comment]
ok i just looked into the code and i made a thinking mistake.
You need these files only serversided because the data is automatically are synchorinzed (the current weight & max weight) and effects are serverside only.
Though the config needs to be client side to show the user how much each item is weight.
But that is only tooltip information.

**Comment by fitnfnsk** [comment]
And how to make the speed decrease at 50% of the filled weight?
