### ISSUE TITLE
Bug

### ISSUE THREAD

**Issue by planyte** [TinyModularThings/Player-Weight#18]
My player open furnace After that writes to the server console this
https://cdn.discordapp.com/attachments/663114062061764622/671705739705843726/ScreenShot_20200128161811.png

**Comment by planyte** [comment]
[crash-2020-01-28_16.06.24-server.txt](https://github.com/TinyModularThings/Player-Weight/files/4122894/crash-2020-01-28_16.06.24-server.txt)
[crash-2020-01-28_16.23.02-server.txt](https://github.com/TinyModularThings/Player-Weight/files/4122896/crash-2020-01-28_16.23.02-server.txt)

**Comment by planyte** [comment]
https://cdn.discordapp.com/attachments/663114062061764622/671730167743250432/ScreenShot_20200128175502.png
https://cdn.discordapp.com/attachments/663114062061764622/671730433381236736/ScreenShot_20200128175642.png

**Comment by planyte** [comment]
Magma server core 1.12.2

**Comment by Speiger** [comment]
Ok thanks, I am not sure how to fix that.

**Comment by planyte** [comment]
I was told that this is like easy to fix

**Comment by planyte** [comment]
It's making players listen in on containers which they're already listening to. That may be something I can fix, but it should be easy on their side to do a small check 
Quote tomdodd4598

**Comment by Speiger** [comment]
Eh yeah, only difference is that the player container should never ever call "OnContainerOpen"
unless forge changed something.
Also the issue is that I would have to keep track of each container instance and validate that it isnt opened twice, and deleting a listener isnt possible since you are only allowed to do that ClientSided.

So something was changed.
If he knows how to fix it then ask him to submit a patch, I will test the patch and if it works for me I am throwing out a update.

Right now a couple bigger projects eat most of the time.

**Comment by planyte** [comment]
I can give him a discord it will be easier for you to talk to him in the DS yourself he said that I would write a report here

**Comment by tomdodd4598** [comment]
Checking through my source code, I don't think I'm calling `OnContainerOpen` anywhere, but the crash report doesn't indicate to me that NC is involved anyway, so I think we're barking up the complete wrong tree. I don't think there's anything wrong with what your mod is doing - instead I imagine it could well be a core mod such as Magma causing it in the background.

**Comment by planyte** [comment]
https://github.com/magmafoundation/Magma

**Comment by planyte** [comment]
https://cdn.discordapp.com/attachments/663114062061764622/671806357267283968/ScreenShot_20200128225821.png plugins 
[crash-2020-01-28_20.19.20-server.txt](https://github.com/TinyModularThings/Player-Weight/files/4124411/crash-2020-01-28_20.19.20-server.txt)
[crash-2020-01-28_19.56.17-server.txt](https://github.com/TinyModularThings/Player-Weight/files/4124415/crash-2020-01-28_19.56.17-server.txt)

**Comment by planyte** [comment]
When a player has died the console highlights this
https://cdn.discordapp.com/attachments/663114062061764622/671730167743250432/ScreenShot_20200128175502.png
https://cdn.discordapp.com/attachments/663114062061764622/671730433381236736/ScreenShot_20200128175642.png

**Comment by Speiger** [comment]
![opera_2020-01-29_14-16-31](https://user-images.githubusercontent.com/2556269/73359819-f8d38100-42a1-11ea-987d-821e40bac5b2.png)
All your discord pics are like this.

**Comment by planyte** [comment]
https://yadi.sk/d/PYuEBdvJOJVtiw logs

**Comment by planyte** [comment]
These are screenshots from the discord

**Comment by planyte** [comment]
https://discord.gg/Pw8uZVU There you will find my screenshots

**Comment by planyte** [comment]
In the general section

**Comment by planyte** [comment]
Time of screenshot today, 6.49-6.50

**Comment by Speiger** [comment]
@turbodiesel4598 i missed your message. This looks really weird to me. I wonder if the respawn logic has something to do with it. But you could be right to. I am testing the crashcase now and see what exactly it is.

**Comment by Speiger** [comment]
@planyte @turbodiesel4598 is right this has nothing to do with my mod. It seems like that the base you build your stuff on has a bug and does not reset the player container everytime the player respawns. Because i killed myself like 10 times (5 times in a singleplayer world & 5 times on a quickhosted server)
and i wasnt able to generate a crash.
